// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdp9JlPFhbAqNp4v2PpDB9pLOFCIC2A1U',
    appId: '1:14026475443:web:f0a4f98e0389d10226edc6',
    messagingSenderId: '14026475443',
    projectId: 'xp-game-f001a',
    authDomain: 'xp-game-f001a.firebaseapp.com',
    storageBucket: 'xp-game-f001a.firebasestorage.app',
    measurementId: 'G-PYM8BYKV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLoKD1Q26ni69wL4T46tdD_RN_LFEVvHY',
    appId: '1:14026475443:android:abbfb19858e5d11926edc6',
    messagingSenderId: '14026475443',
    projectId: 'xp-game-f001a',
    storageBucket: 'xp-game-f001a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQy9eFdAyD8VPfNDAPqWRn3ayAARRKG0',
    appId: '1:14026475443:ios:70fe7553ee0583fd26edc6',
    messagingSenderId: '14026475443',
    projectId: 'xp-game-f001a',
    storageBucket: 'xp-game-f001a.firebasestorage.app',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQy9eFdAyD8VPfNDAPqWRn3ayAARRKG0',
    appId: '1:14026475443:ios:70fe7553ee0583fd26edc6',
    messagingSenderId: '14026475443',
    projectId: 'xp-game-f001a',
    storageBucket: 'xp-game-f001a.firebasestorage.app',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdp9JlPFhbAqNp4v2PpDB9pLOFCIC2A1U',
    appId: '1:14026475443:web:782806e0a8baad2b26edc6',
    messagingSenderId: '14026475443',
    projectId: 'xp-game-f001a',
    authDomain: 'xp-game-f001a.firebaseapp.com',
    storageBucket: 'xp-game-f001a.firebasestorage.app',
    measurementId: 'G-RD3Z79XQW3',
  );
}
